void rev_string(char *s);
void puts_half(char *str);
void puts2(char *str);
int _putchar(char c);
void _puts(char *str);
int _strlen(char *s);
void swap_int(int *a, int *b);
void reset_to_98(int *n);
void print_array(int *a, int n);
void print_rev(char *s);
int _atoi(char *s);
